name: movies_land
version: 1.0.0+1
description: Movies Land.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  get: 4.6.1
  iconly: 1.0.1
  cupertino_icons: 1.0.2
  intl: 0.17.0
  cloud_firestore: 3.1.12
  flutter_spinkit: 5.1.0
  flutter_speed_dial: 5.1.0
  animated_splash_screen: 1.2.0
  cached_network_image: 3.2.0
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: 0.9.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  image_path: "assets/app_icon.png"
  android: "app_icon"
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/app_icon_round.png

