name: movies_land
version: 1.0.0+1
description: Movies Land.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  get: 4.6.1
  intl: 0.17.0
  iconly: 1.0.1
  flutter_spinkit: 5.1.0
  cupertino_icons: 1.0.2
  cloud_firestore: 3.1.12
  flutter_speed_dial: 5.1.0
  cached_network_image: 3.2.0
  animated_splash_screen: 1.2.0
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: 0.9.0
  url_strategy: 0.2.0
  build_runner: 2.1.10
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/app_icon_round.png
  android: app_icon_round
  ios: true
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/
    - assets/app_logo.png
    - assets/app_icon.png
    - assets/app_icon_round.png
  uses-material-design: true

