name: movies_land
version: 1.0.0+1
description: Movies Land.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  cupertino_icons: 1.0.2
  get: 4.6.1
  #firebase_core: 1.14.1
  cloud_firestore: 3.1.12
  #firebase_auth: 3.3.14
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test:
    sdk: flutter

flutter_icons: 
  image_path: assets/app_icon_round.png
  android: app_icon_round
  ios: true
  remove_alpha_ios: true

flutter_launcher_name: 
  name: Movies Land

flutter: 
  assets: 
    - assets/
  uses-material-design: true

