name: movies_land
version: 1.0.0+1
description: Movies Land App.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  video_player: 2.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter_launcher_name: 
  name: Movies Land

flutter: 
  uses-material-design: true

