name: movies_land
version: 1.0.0+1
description: Movies Land.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  get: ^4.6.5
  intl: 0.17.0
  iconly: 1.0.1
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.4
  flutter_spinkit: 5.1.0
  cloud_firestore: ^3.1.13
  flutter_speed_dial: ^6.0.0
  cached_network_image: ^3.2.2
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  url_strategy: 0.2.0
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter

flutter_icons: 
  image_path: assets/app_icon_round.png
  android: app_icon_round
  ios: true
  remove_alpha_ios: true

flutter_launcher_name:
  name: Movies Land


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/app_logo.png
    - assets/app_icon.png
    - assets/app_icon_round.png

