name: food_delivery
version: 1.0.0+1
publish_to: none
description: Food Delivery App.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  get: 4.6.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  #change_app_package_name: ^1.0.0
  #flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.9.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  image_path: "assets/app_icon.png"
  android: "app_icon"
  ios: true
  remove_alpha_ios: true

flutter_launcher_name:
  name: "Foodie"

flutter: 
  uses-material-design: true
  assets:
    - assets/
