name: food_delivery
version: 1.0.0+1
description: Food Delivery App.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  get: 4.6.1
  cupertino_icons: 1.0.2
  animated_splash_screen: 1.2.0
  flutter_spinkit: 5.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/app_icon_round.png
  android: app_icon_round
  ios: true
  remove_alpha_ios: true

flutter_launcher_name: 
  name: Foodie

flutter: 
  assets: 
    - assets/
  uses-material-design: true

